#!/bin/sh

regex='@company\.com$'

email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
	echo Your email $email satisfies Git policy
	exit 0
else
	echo "Your email $email diesn't satisfy Git poilicy"
	exit 1
fi